name: "Terraform CI - Basic"

on:
  push:
    branches:
      - main
  

jobs:
  terraform:
    name: "Terraform Init, Validate, and Plan"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: "Checkout code"
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.0"

      # Step 3: Initialize Terraform
      - name: "Terraform Init"
        run: terraform init -input=false

      # Step 4: Check formatting
      - name: "Terraform Fmt Check"
        run: terraform fmt -check

      # Step 5: Validate the configuration
      - name: "Terraform Validate"
        run: terraform validate

      # Step 6: Generate the execution plan
      - name: "Terraform Plan"
        run: terraform plan -input=false
        
      # Step 6: Generate the execution plan
      - name: "Terraform apply"
        run: terraform apply -input=false -auto-approve
        
