name: "Terraform CI - Basic"

on:
  push:
    branches:
      - main
    paths:
      - 'Terraform/**'  # Only trigger when Terraform files change

jobs:
  terraform:
    name: "Terraform Init, Validate, Plan, and Apply"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: "Checkout code"
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.0"

      # Step 3: Configure AWS Credentials
      - name: "Configure AWS Credentials"
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      # Step 4: Initialize Terraform
      - name: "Terraform Init"
        run: terraform init -input=false
        working-directory: terraform/

      # Step 5: Check Terraform formatting
      - name: "Terraform Fmt Check"
        run: terraform fmt -check
        working-directory: terraform/

      # Step 6: Validate Terraform Configuration
      - name: "Terraform Validate"
        run: terraform validate
        working-directory: terraform/

      # Step 7: Generate Terraform Plan
      - name: "Terraform Plan"
        run: terraform plan -input=false
        working-directory: terraform/

      # Step 8: Apply Terraform Changes
      # - name: "Terraform Apply"
      #   run: terraform apply -input=false -auto-approve
      #   working-directory: terraform/


